=== Komatsu52/DAW/TPC/T2/record.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT record (projectname, header, workteam, abstract, deliverables, date) >

<!ELEMENT projectname (#PCDATA) >

<!ELEMENT header (keyname, title, subtitle?, begindate, enddate, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begindate (#PCDATA) >
<!ELEMENT enddate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
    href CDATA #REQUIRED >

<!ELEMENT workteam (person|(person, person)|(person, person, person)) >
<!ELEMENT person (number, name, email) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ATTLIST name
    href CDATA #IMPLIED >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (paragraph+) >
<!ELEMENT paragraph (#PCDATA|bold|italic|underline|link)* >
<!ELEMENT bold (#PCDATA|italic|underline)* >
<!ELEMENT italic (#PCDATA|bold|underline)* >
<!ELEMENT underline (#PCDATA|bold|italic)* >
<!ELEMENT link (#PCDATA) >
<!ATTLIST link
    href CDATA #REQUIRED >

<!ELEMENT deliverables (link+) >

<!ELEMENT date (#PCDATA) >

=== Komatsu52/DAW/TPC/T2/record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE record SYSTEM "file:/home/goncalo/%C3%81rea%20de%20Trabalho/4%C2%BAAno/Complementares/DAW2020/TPC/T2/record.dtd">
<record>
    <projectname>TPC2</projectname>
    <header>
        <keyname>Relatório do TPC2</keyname>
        <title>DTDs</title>
        <subtitle>Segundo TPC de DAW</subtitle>
        <begindate>25-10-2020</begindate>
        <enddate>28-10-2020</enddate>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <person>
            <number>a85731</number>
            <name href="https://github.com/Komatsu52">Gonçalo José Azevedo Esteves</name>
            <email>a85731@alunos.uminho.pt</email>
        </person>
    </workteam>
    <abstract>
        <paragraph>
            <text></text>
        </paragraph>
    </abstract>
    <deliverables>
        <link href="">Ficheiro DTD</link>
        <link href="">Ficheiro XML</link>
    </deliverables>
    <date>28-10-2020</date>
</record>
